name: Commitlint
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Lint commits and PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint (commits)
        uses: wagoid/commitlint-github-action@v6
      - name: PR title (semantic)
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
