name: Jules Checks

on:
  pull_request:

jobs:
  jules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to compare branches

      - name: Generate PR diff summary
        run: |
          echo "### PR Diff Summary" > jules_summary.txt
          echo '```diff' >> jules_summary.txt
          git diff --name-status origin/${{ github.base_ref }}...origin/${{ github.head_ref }} >> jules_summary.txt
          echo '```' >> jules_summary.txt

      - name: Run Jules Tests
        id: tests
        run: bash scripts/jules-run-tests.sh
        continue-on-error: true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jules-pr-${{ github.event.number }}
          path: |
            jules_summary.txt
            jules_report.md

      - name: Post PR Comment
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('jules_summary.txt', 'utf8');
            const report = fs.readFileSync('jules_report.md', 'utf8');

            const body = `
            ${summary}

            ---

            ${report}

            **Test Status:** ${{ steps.tests.outcome == 'success' ? '✅ Passed' : '❌ Failed' }}
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
